"""Realtime event types and payloads for multi-device synchronization."""

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class RealtimeEventType(str, Enum):
    """Events broadcast to connected session clients."""

    SESSION_CREATED = "SESSION_CREATED"
    SESSION_UPDATED = "SESSION_UPDATED"
    SESSION_SNAPSHOT = "SESSION_SNAPSHOT"
    MESSAGE_CREATED = "MESSAGE_CREATED"
    CHAT_MESSAGE = "CHAT_MESSAGE"
    MESSAGE_UPDATED = "MESSAGE_UPDATED"
    AI_RESPONSE_STARTED = "AI_RESPONSE_STARTED"
    AI_RESPONSE_CHUNK = "AI_RESPONSE_CHUNK"
    AI_RESPONSE_COMPLETED = "AI_RESPONSE_COMPLETED"
    ASSISTANT_STATUS = "ASSISTANT_STATUS"
    VOICE_TRANSCRIPT = "VOICE_TRANSCRIPT"
    MEASUREMENT_CREATED = "MEASUREMENT_CREATED"
    IMAGE_CREATED = "IMAGE_CREATED"
    IMAGE_UPDATED = "IMAGE_UPDATED"
    ANNOTATION_CREATED = "ANNOTATION_CREATED"
    DIAGNOSTIC_TEST_UPDATED = "DIAGNOSTIC_TEST_UPDATED"
    DIAGNOSTIC_UPDATED = "DIAGNOSTIC_UPDATED"
    DIAGNOSTIC_TEST_STARTED = "DIAGNOSTIC_TEST_STARTED"
    DIAGNOSTIC_TEST_COMPLETED = "DIAGNOSTIC_TEST_COMPLETED"
    TOOL_STATE_CHANGED = "TOOL_STATE_CHANGED"
    DEVICE_CONNECTED = "DEVICE_CONNECTED"
    DEVICE_DISCONNECTED = "DEVICE_DISCONNECTED"
    DEVICE_HEARTBEAT = "DEVICE_HEARTBEAT"
    SESSION_RESUMED = "SESSION_RESUMED"
    SESSION_STATE_UPDATED = "SESSION_STATE_UPDATED"
    STATE_UPDATE_REJECTED = "STATE_UPDATE_REJECTED"
    AGENT_CONNECTED = "AGENT_CONNECTED"
    AGENT_DISCONNECTED = "AGENT_DISCONNECTED"
    AGENT_HEARTBEAT = "AGENT_HEARTBEAT"
    AGENT_TEST_RESULT = "AGENT_TEST_RESULT"
    TOOL_EXECUTION_STARTED = "TOOL_EXECUTION_STARTED"
    TOOL_EXECUTION_COMPLETED = "TOOL_EXECUTION_COMPLETED"
    TOOL_EXECUTE_RESULT = "TOOL_EXECUTE_RESULT"
    REPAIR_DEVICE_DETECTED = "REPAIR_DEVICE_DETECTED"
    REPAIR_DEVICE_LIST_UPDATED = "REPAIR_DEVICE_LIST_UPDATED"
    REPAIR_DEVICE_ASSOCIATED = "REPAIR_DEVICE_ASSOCIATED"
    REPAIR_DEVICE_UNASSOCIATED = "REPAIR_DEVICE_UNASSOCIATED"
    REPAIR_DEVICE_DISCONNECTED = "REPAIR_DEVICE_DISCONNECTED"


class RealtimeEvent(BaseModel):
    """Realtime envelope sent to subscribed clients."""

    id: str
    repair_session_id: str
    event_type: RealtimeEventType
    payload: dict[str, Any] = Field(default_factory=dict)
    emitted_at: datetime | None = None
    source_client_device_id: str | None = None
